CREATE TABLE [dbo].[tblOneTimeToken]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [UserId] UNIQUEIDENTIFIER NOT NULL, 
    [Purpose] NVARCHAR(50) NOT NULL, 
    [TokenHash] VARBINARY(64) NOT NULL, 
    [ExpiresAt] DATETIME2 NOT NULL, 
    [ConsumedAt] DATETIME2 NULL,
    FOREIGN KEY (UserId) REFERENCES tblUsers(Id) ON DELETE CASCADE
)
