CREATE TABLE [dbo].[tblRefreshTokens]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [UserId] UNIQUEIDENTIFIER NOT NULL, 
    [TokenHash] VARBINARY(64) NOT NULL, 
    [IssueAt] DATETIME2 NOT NULL, 
    [ExpiresAt] DATETIME2 NOT NULL, 
    [Device] NVARCHAR(200) NULL, 
    [IpAddress] NVARCHAR(64) NULL, 
    [RevokedAt] DATETIME2 NULL, 
    [ReplacedByTokenHash] VARBINARY(64) NULL,
    FOREIGN KEY (UserId) REFERENCES tblUsers(Id) ON DELETE CASCADE
)
