CREATE TABLE [dbo].[tblUsers]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Email] NVARCHAR(256) NOT NULL UNIQUE, 
    [EmailConfirmed] BIT NOT NULL DEFAULT 0, 
    [PasswordHash] NVARCHAR(200) NOT NULL, 
    [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), 
    [UpdateAt] DATETIME2 NULL 
)
