CREATE TABLE [dbo].[tblUsers]
(
	[flngUserKey] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [fstrEmail] NVARCHAR(256) NOT NULL UNIQUE, 
    [fblnEmailConfirmed] INT NOT NULL DEFAULT 0, 
    [fstrPasswordHash] NVARCHAR(200) NOT NULL, 
    [fdtmCreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), 
    [fdtmUpdateAt] DATETIME2 NULL 
)

GO
