CREATE TABLE [dbo].[tblUserRoles]
(
	[UserId] UNIQUEIDENTIFIER NOT NULL, 
    [RoleId] UNIQUEIDENTIFIER NOT NULL,
	PRIMARY KEY (UserId, RoleId),
	FOREIGN KEY (UserId) REFERENCES tblUsers(Id) ON DELETE CASCADE,
	FOREIGN KEY (RoleId) REFERENCES tblRole(Id) ON DELETE CASCADE
)
